name: Notify Discord on Push

on:
  push:
    branches:
      - main  # Cambia a tu rama principal si es diferente
      - develop
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
                "username": "GitHub Actions",
                "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                "embeds": [{
                  "title": "🚀 Nuevo Push en el Frontend!",
                  "description": "Se ha realizado un nuevo cambio en la rama `main`.",
                  "color": 3447003,
                  "fields": [
                    {
                      "name": "Repositorio",
                      "value": "'${{ github.repository }}'"
                    },
                    {
                      "name": "Commit",
                      "value": "'${{ github.event.head_commit.message }}'"
                    },
                    {
                      "name": "Autor",
                      "value": "'${{ github.event.head_commit.author.name }}'"
                    }
                  ]
                }]
              }' \
          ${{ secrets.DISCORD_WEBHOOK }}
